name = "AAS247Julia"

[deps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[compat]
AMDGPU = "2"
CSV = "0.10"
CUDA = "5"
DelimitedFiles = "1"
DrWatson = "2.19.1"
HypertextLiteral = "0.9"
LinearAlgebra = "1"
Metal = "1"
Pluto = "0.20.20"
PlutoUI = "0.7"
Revise = "3"
Symbolics = "7"
julia = "1.11.7"
